[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  VITE_API_URL = "https://cashcompass-api.onrender.com/api/v1"
  VITE_APP_NAME = "CashCompass"
  VITE_APP_VERSION = "1.0.0"
  VITE_NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
