# Render.com Deployment Configuration
services:
  - type: web
    name: cashcompass-api
    env: node
    region: oregon
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /api/v1/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGO_URI
        fromDatabase:
          name: cashcompass-mongodb
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRE
        value: 30d
      - key: BCRYPT_ROUNDS
        value: 12
      - key: FRONTEND_URL
        value: https://cashcompass-frontend.onrender.com
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 100

databases:
  - name: cashcompass-mongodb
    databaseName: cashcompass_production
    user: cashcompass_user
    region: oregon
    plan: starter
